import asyncio
import logging
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any, Optional

import httpx
from pymongo import ReturnDocument

from ..database import get_db
from ..services.dm import SendStatus, send_dm

logger = logging.getLogger(__name__)

# Retry / backoff config
MAX_SEND_ATTEMPTS = 5       # max 500-retries per idempotency attempt
BACKOFF_BASE = 2.0          # seconds
MAX_BACKOFF = 30.0          # seconds cap

# Worker loop
POLL_INTERVAL = 1.0                # seconds to wait when no work found
STUCK_CLAIM_TIMEOUT_SECONDS = 120  # reclaim deliveries stuck in "claimed"

# PseudoGram rate limit
RATE_LIMIT_MAX = 10    # max sends per window
RATE_LIMIT_WINDOW = 60 # seconds


async def acquire_rate_limit_slot(db) -> Optional[float]:
    """
    Atomically try to acquire one DM send slot using a MongoDB aggregation pipeline update.

    The rate_limit document keeps a sliding window of send timestamps.
    The aggregation pipeline atomically:
      1. Evicts timestamps older than RATE_LIMIT_WINDOW seconds.
      2. Checks if count < RATE_LIMIT_MAX; if so, appends current timestamp.

    Returns:
        None  — slot acquired, proceed to send.
        float — seconds to wait before retrying (rate limited).
    """
    now = datetime.now(timezone.utc)
    window_cutoff = now - timedelta(seconds=RATE_LIMIT_WINDOW)

    result = await db.rate_limit.find_one_and_update(
        {"_id": "dm_rate_limit"},
        [
            # Stage 1: evict expired timestamps
            {
                "$set": {
                    "send_times": {
                        "$filter": {
                            "input": {"$ifNull": ["$send_times", []]},
                            "as": "t",
                            "cond": {"$gt": ["$$t", window_cutoff]},
                        }
                    }
                }
            },
            # Stage 2: conditionally append current timestamp
            {
                "$set": {
                    "can_send": {"$lt": [{"$size": "$send_times"}, RATE_LIMIT_MAX]},
                    "send_times": {
                        "$cond": {
                            "if": {"$lt": [{"$size": "$send_times"}, RATE_LIMIT_MAX]},
                            "then": {"$concatArrays": ["$send_times", [now]]},
                            "else": "$send_times",
                        }
                    },
                    # oldest_in_window is computed from send_times BEFORE appending (Stage 1 result)
                    "oldest_in_window": {"$min": "$send_times"},
                }
            },
        ],
        upsert=True,
        return_document=ReturnDocument.AFTER,
    )

    if result and result.get("can_send", True):
        return None  # slot acquired

    # Rate limited — calculate how long to wait
    if result and result.get("oldest_in_window"):
        oldest = result["oldest_in_window"]
        if oldest.tzinfo is None:
            oldest = oldest.replace(tzinfo=timezone.utc)
        wait_until = oldest + timedelta(seconds=RATE_LIMIT_WINDOW)
        wait_seconds = (wait_until - now).total_seconds()
        return max(1.0, wait_seconds)

    return float(RATE_LIMIT_WINDOW)


async def process_delivery(
    delivery: dict[str, Any],
    db,
    client: httpx.AsyncClient,
) -> None:
    """
    Process a single delivery that has already been atomically claimed (status='claimed').

    Idempotency-key contract:
      - delivery['idempotency_key'] is reused across 500 retries (same attempt).
      - A new key is only generated by the reconciliation worker after PseudoGram
        confirms terminal 'failed' status on a previously accepted DM.
    """
    delivery_id = delivery["delivery_id"]
    user_id = delivery["user_id"]
    comment_id = delivery["comment_id"]
    message = delivery["message"]
    idempotency_key = delivery["idempotency_key"]
    attempts = delivery.get("attempts", 0)
    now = datetime.now(timezone.utc)

    # --- Rate limit check ---
    wait_seconds = await acquire_rate_limit_slot(db)
    if wait_seconds is not None:
        logger.info(
            "Rate limited — releasing delivery %s back to pending, retry in %.1fs",
            delivery_id,
            wait_seconds,
        )
        await db.deliveries.update_one(
            {"delivery_id": delivery_id},
            {
                "$set": {
                    "status": "pending",
                    "retry_after": now + timedelta(seconds=wait_seconds),
                    "updated_at": now,
                }
            },
        )
        return

    # --- Send DM ---
    result = await send_dm(
        client,
        recipient_user_id=user_id,
        message=message,
        comment_id=comment_id,
        idempotency_key=idempotency_key,
    )
    now = datetime.now(timezone.utc)
    next_attempts = attempts + 1

    if result.status == SendStatus.ACCEPTED:
        # 202 — queued by PseudoGram; reconciliation will confirm actual delivery
        await db.deliveries.update_one(
            {"delivery_id": delivery_id},
            {
                "$set": {
                    "status": "accepted",
                    "dm_id": result.dm_id,
                    "attempts": next_attempts,
                    "updated_at": now,
                }
            },
        )
        logger.info("DM accepted: delivery=%s dm_id=%s", delivery_id, result.dm_id)

    elif result.status == SendStatus.RATE_LIMITED:
        # 429 — honor Retry-After from PseudoGram (our rate limiter may have miscounted)
        retry_secs = result.retry_after_seconds or 60.0
        await db.deliveries.update_one(
            {"delivery_id": delivery_id},
            {
                "$set": {
                    "status": "pending",
                    "retry_after": now + timedelta(seconds=retry_secs),
                    "attempts": next_attempts,
                    "updated_at": now,
                }
            },
        )
        logger.warning(
            "DM 429 — delivery=%s retry_after=%.1fs", delivery_id, retry_secs
        )

    elif result.status == SendStatus.TRANSIENT_FAILURE:
        # 500 / network error — retry with SAME idempotency_key (original may have been received)
        if next_attempts >= MAX_SEND_ATTEMPTS:
            await db.deliveries.update_one(
                {"delivery_id": delivery_id},
                {
                    "$set": {
                        "status": "failed",
                        "attempts": next_attempts,
                        "updated_at": now,
                    }
                },
            )
            logger.error(
                "DM permanently failed after %d attempts: delivery=%s",
                next_attempts,
                delivery_id,
            )
        else:
            backoff = min(BACKOFF_BASE ** next_attempts, MAX_BACKOFF)
            await db.deliveries.update_one(
                {"delivery_id": delivery_id},
                {
                    "$set": {
                        "status": "pending",
                        "retry_after": now + timedelta(seconds=backoff),
                        "attempts": next_attempts,
                        "updated_at": now,
                    }
                },
            )
            logger.warning(
                "DM transient error — delivery=%s attempt=%d/%d retry_in=%.1fs",
                delivery_id,
                next_attempts,
                MAX_SEND_ATTEMPTS,
                backoff,
            )

    elif result.status == SendStatus.PERMANENT_FAILURE:
        # 400 or other 4xx — do not retry
        await db.deliveries.update_one(
            {"delivery_id": delivery_id},
            {
                "$set": {
                    "status": "failed",
                    "attempts": next_attempts,
                    "updated_at": now,
                }
            },
        )
        logger.error(
            "DM permanent failure HTTP %d: delivery=%s",
            result.http_status,
            delivery_id,
        )


async def run_dm_worker() -> None:
    """
    Background worker that atomically claims and processes pending deliveries.

    Uses find_one_and_update to claim exactly one delivery at a time,
    preventing concurrent workers from double-processing the same job.
    """
    logger.info("DM worker started")

    async with httpx.AsyncClient() as client:
        while True:
            try:
                db = get_db()
                now = datetime.now(timezone.utc)

                # Reclaim deliveries stuck in "claimed" — handles crashes / unexpected exits
                stuck_cutoff = now - timedelta(seconds=STUCK_CLAIM_TIMEOUT_SECONDS)
                await db.deliveries.update_many(
                    {"status": "claimed", "updated_at": {"$lt": stuck_cutoff}},
                    {"$set": {"status": "pending", "updated_at": now}},
                )

                # Atomically claim one ready delivery: pending → claimed
                delivery = await db.deliveries.find_one_and_update(
                    {
                        "status": "pending",
                        "$or": [
                            {"retry_after": None},
                            {"retry_after": {"$exists": False}},
                            {"retry_after": {"$lte": now}},
                        ],
                    },
                    {"$set": {"status": "claimed", "updated_at": now}},
                    return_document=ReturnDocument.AFTER,
                )

                if delivery is None:
                    await asyncio.sleep(POLL_INTERVAL)
                    continue

                await process_delivery(delivery, db, client)

            except asyncio.CancelledError:
                logger.info("DM worker cancelled")
                raise
            except Exception as exc:
                logger.exception("Unexpected error in DM worker: %s", exc)
                await asyncio.sleep(POLL_INTERVAL)

    logger.info("DM worker stopped")
